import CombatLogParser from '../CombatLogParser';
import { GuideProps, Section, SubSection } from 'interface/guide';
import { IntroSection } from './guide/IntroSection';
import { SpellLink } from 'interface';
import SPELLS from 'common/SPELLS/deathknight';
import TALENTS from 'common/TALENTS/deathknight';
import PreparationSection from 'interface/guide/components/Preparation/PreparationSection';
import Cooldowns from './guide/CooldownSection';
import { FoundationDowntimeSection } from 'interface/guide/foundation/FoundationDowntimeSection';
import { t } from '@lingui/core/macro';
import { Trans } from '@lingui/react/macro';

export default function Guide({ modules, info }: GuideProps<typeof CombatLogParser>) {
  return (
    <>
      <IntroSection />

      <Section
        title={t({
          id: 'guide.deathknight.unholy.sections.coreSpells.title',
          message: 'Core Spells and Buffs',
        })}
      >
        {info.combatant.hasTalent(TALENTS.PUTREFY_TALENT) && modules.putrefy.guideSubsection}
      </Section>

      <Section
        title={t({
          id: 'guide.deathknight.unholy.sections.activeTime.title',
          message: 'Active Time',
        })}
      >
        <FoundationDowntimeSection />
      </Section>

      <Section
        title={t({
          id: 'guide.deathknight.unholy.sections.cooldownTracking.title',
          message: 'Cooldown Tracking',
        })}
      >
        <Cooldowns />
      </Section>

      <Section
        title={t({
          id: 'guide.deathknight.unholy.sections.resourceUse.title',
          message: 'Resource Use',
        })}
      >
        <SubSection
          title={t({
            id: 'guide.deathknight.unholy.sections.resourceUse.runes.title',
            message: 'Runes',
          })}
        >
          <div>
            <p>
              <Trans id="guide.deathknight.unholy.sections.resourceUse.runes.summary1">
                Runes are Unholy’s core resource used to cast key abilities. Up to three runes can
                regenerate at a time and managing them efficiently is crucial for maintaining a
                smooth rotation. When you sit on 4 or more Runes, you are overcapping and wasting
                regeneration time. On the other hand, having no Runes available can mean you’re
                starved during important burst windows.
              </Trans>
            </p>
          </div>

          <div>
            <p>
              <Trans id="guide.deathknight.unholy.sections.resourceUse.runes.summary2">
                This graph shows your Rune availability throughout the fight. Frequent spikes to 5–6
                may indicate overcapping, while long periods near 0 may suggest resource starvation
                or poor alignment with cooldowns.
              </Trans>
            </p>
          </div>

          <div>{modules.runeGraph.plot}</div>
        </SubSection>

        <SubSection
          title={t({
            id: 'guide.deathknight.unholy.sections.resourceUse.runicPower.title',
            message: 'Runic Power',
          })}
        >
          <div>
            <p>
              <Trans id="guide.deathknight.unholy.sections.resourceUse.runicPower.summary1">
                Runic Power is your secondary resource, generated by spending Runes with abilities.
                Your main way to spend it is through <SpellLink spell={SPELLS.DEATH_COIL} /> (or{' '}
                <SpellLink spell={SPELLS.EPIDEMIC} /> in AoE situations), which helps maintain
                pressure and fuel your Runic Corruption passive — increasing Rune regeneration
                speed.
              </Trans>
            </p>
          </div>

          <div>
            <p>
              <Trans id="guide.deathknight.unholy.sections.resourceUse.runicPower.summary2">
                For optimal efficiency, avoid overcapping on Runic Power. You should aim to spend it
                regularly to keep your Rune regeneration flowing. Short spikes are normal, but
                staying near the cap for extended periods usually means missed Death Coils or
                inefficient GCD usage.
              </Trans>
            </p>
          </div>

          <div>
            <p>
              <Trans id="guide.deathknight.unholy.sections.resourceUse.runicPower.summary3">
                This chart displays your Runic Power over time. Watch for flat peaks as signs of
                waste and opportunities to tighten your resource flow.
              </Trans>
            </p>
          </div>

          <div>{modules.runicPowerGraph.plot}</div>
        </SubSection>
      </Section>
      <PreparationSection />
    </>
  );
}
