import { t } from '@lingui/core/macro';
import { PerformanceMark } from 'interface/guide';
import Analyzer, { Options, SELECTED_PLAYER } from 'parser/core/Analyzer';
import SPELLS from 'common/SPELLS/hunter';
import TALENTS from 'common/TALENTS/hunter';
import Events, { CastEvent } from 'parser/core/Events';
import { CooldownExpandableItem } from 'interface/guide/components/CooldownExpandable';
import SpellLink from 'interface/SpellLink';
import { QualitativePerformance } from 'parser/ui/QualitativePerformance';
import { TooltipElement } from 'interface/Tooltip';

export const TAKEDOWN_WINDOW_MS = 8_000;
export const WINDOW_EXTENSION_MS = 3_000;
const MAX_TIP_STACKS = 3;

export interface TakedownCast {
  castEvent: CastEvent;
  isFirstTakedown: boolean;
  tipStacks: number;
  wastedTipStacks: number;
  castsInWindow: CastEvent[];
  windowEnd: number;
}

export default class Takedown extends Analyzer {
  readonly isPackLeader: boolean;
  private readonly hasTwinFangs: boolean;
  private readonly kcStacksGenerated: number;

  readonly takedownCasts: TakedownCast[] = [];

  constructor(options: Options) {
    super(options);

    this.isPackLeader = !this.selectedCombatant.hasTalent(TALENTS.MOONLIGHT_CHAKRAM_TALENT);
    this.hasTwinFangs = this.selectedCombatant.hasTalent(TALENTS.TWIN_FANGS_TALENT);
    this.kcStacksGenerated = this.selectedCombatant.hasTalent(TALENTS.PRIMAL_SURGE_TALENT) ? 2 : 1;

    this.active = this.selectedCombatant.hasTalent(TALENTS.TAKEDOWN_TALENT);

    if (!this.active) {
      return;
    }

    this.addEventListener(Events.cast.by(SELECTED_PLAYER), this.onAnyCast);
  }

  private get currentWindow(): TakedownCast | undefined {
    return this.takedownCasts.at(-1);
  }

  private onAnyCast(event: CastEvent) {
    if (event.ability.guid === SPELLS.TAKEDOWN_PLAYER.id) {
      this.onTakedown(event);
      return;
    }

    // Accumulate casts that fall inside the current window
    const window = this.currentWindow;
    if (window && event.timestamp <= window.windowEnd) {
      window.castsInWindow.push(event);

      // Kill Command while TotS would overflow the cap = wasted stacks
      if (event.ability.guid === TALENTS.KILL_COMMAND_SURVIVAL_TALENT.id) {
        const tipStacks = this.selectedCombatant.getBuffStacks(SPELLS.TIP_OF_THE_SPEAR_CAST.id);
        const overflow = tipStacks + this.kcStacksGenerated - MAX_TIP_STACKS;
        if (overflow > 0) {
          window.wastedTipStacks += overflow;
        }
      }
    }
  }

  private onTakedown(event: CastEvent) {
    const isFirstTakedown = this.takedownCasts.length === 0;
    const tipStacks = this.selectedCombatant.getBuffStacks(SPELLS.TIP_OF_THE_SPEAR_CAST.id);

    const windowEnd = event.timestamp + TAKEDOWN_WINDOW_MS + WINDOW_EXTENSION_MS;

    this.takedownCasts.push({
      castEvent: event,
      isFirstTakedown,
      tipStacks,
      wastedTipStacks: 0,
      castsInWindow: [],
      windowEnd,
    });
  }

  checklist(cast: TakedownCast): {
    checklist: CooldownExpandableItem[];
    perf: QualitativePerformance;
  } {
    const items: CooldownExpandableItem[] = [];
    let overallPerf = QualitativePerformance.Good;

    const downgrade = (perf: QualitativePerformance) => {
      if (perf < overallPerf) {
        overallPerf = perf;
      }
    };

     // 1. Tip of the Spear stacks at cast
    if (this.hasTwinFangs) {
      // Twin Fangs generates TotS during Takedown, so ideally enter with 0 stacks
      const tipPerf =
        cast.tipStacks === 0 ? QualitativePerformance.Good : QualitativePerformance.Ok;
      downgrade(tipPerf);
      items.push({
        label: (
          <>
            <SpellLink spell={SPELLS.TIP_OF_THE_SPEAR_CAST} />
            {t({
              id: 'hunter.survival.takedown.tipAtCast.p1',
              message: ' at cast ',
            })}
            <TooltipElement
              content={
                <>
                  {t({
                    id: 'hunter.survival.takedown.twinFangsTipTooltip.p1',
                    message: 'With ',
                  })}
                  <SpellLink spell={TALENTS.TWIN_FANGS_TALENT} />
                  {t({
                    id: 'hunter.survival.takedown.twinFangsTipTooltip.p2',
                    message: ', Takedown generates ',
                  })}
                  <SpellLink spell={SPELLS.TIP_OF_THE_SPEAR_CAST} />
                  {t({
                    id: 'hunter.survival.takedown.twinFangsTipTooltip.p3',
                    message: ' stacks on its own. Enter Takedown with 0 stacks to avoid wasting stacks generated by Twin Fangs.',
                  })}
                </>
              }
            >
              (?)
            </TooltipElement>
          </>
        ),
        result: <PerformanceMark perf={tipPerf} />,
        details:
          cast.tipStacks > 0 ? (
            <TooltipElement
              content={t({
                id: 'hunter.survival.takedown.twinFangsStacksDetail',
                message: '{stacks} stack{suffix} at cast — dump before Takedown',
                values: { stacks: cast.tipStacks, suffix: cast.tipStacks !== 1 ? 's' : '' },
              })}
            >
              (?)
            </TooltipElement>
          ) : null,
      });
      } else {
      // Without Twin Fangs, Takedown does not generate stacks — need them going in
      const tipPerf =
        cast.tipStacks >= 2
          ? QualitativePerformance.Good
          : cast.tipStacks === 1
            ? QualitativePerformance.Ok
            : QualitativePerformance.Fail;
      downgrade(tipPerf);
      items.push({
        label: (
          <>
            <SpellLink spell={SPELLS.TIP_OF_THE_SPEAR_CAST} />
            {t({
              id: 'hunter.survival.takedown.tipAtCast.p1',
              message: ' at cast ',
            })}
            <TooltipElement
              content={
                <>
                  {t({
                    id: 'hunter.survival.takedown.noTwinFangsTipTooltip.p1',
                    message: 'Without ',
                  })}
                  <SpellLink spell={TALENTS.TWIN_FANGS_TALENT} />
                  {t({
                    id: 'hunter.survival.takedown.noTwinFangsTipTooltip.p2',
                    message: ', Takedown does not generate ',
                  })}
                  <SpellLink spell={SPELLS.TIP_OF_THE_SPEAR_CAST} />
                  {t({
                    id: 'hunter.survival.takedown.noTwinFangsTipTooltip.p3',
                    message: ' stacks on its own. Use ',
                  })}
                  <SpellLink spell={TALENTS.KILL_COMMAND_SURVIVAL_TALENT} />
                  {t({
                    id: 'hunter.survival.takedown.noTwinFangsTipTooltip.p4',
                    message: ' before Takedown to maximise stacks during the window.',
                  })}
                </>
              }
            >
              (?)
            </TooltipElement>
          </>
        ),
        result: <PerformanceMark perf={tipPerf} />,
        details: (
          <TooltipElement
            content={t({
              id: 'hunter.survival.takedown.noTwinFangsStacksDetail',
              message: '{stacks} stack{suffix} at cast',
              values: { stacks: cast.tipStacks, suffix: cast.tipStacks !== 1 ? 's' : '' },
            })}
          >
            (?)
          </TooltipElement>
        ),
      });
    }

    // 2. Wasted Tip of the Spear (KC cast while capped)
    const tipWastePerf =
      cast.wastedTipStacks === 0 ? QualitativePerformance.Good : QualitativePerformance.Fail;
    downgrade(tipWastePerf);
    items.push({
      label: (
        <>
          <SpellLink spell={SPELLS.TIP_OF_THE_SPEAR_CAST} />
          {t({
            id: 'hunter.survival.takedown.tipWaste.p1',
            message: '  waste ',
          })}
          <TooltipElement
            content={
              <>
                {t({
                  id: 'hunter.survival.takedown.tipWasteTooltip.p1',
                  message: 'Spending ',
                })}
                <SpellLink spell={SPELLS.TIP_OF_THE_SPEAR_CAST} />
                {t({
                  id: 'hunter.survival.takedown.tipWasteTooltip.p2',
                  message: ' stacks always takes priority over generating new ones. Do not use ',
                })}
                <SpellLink spell={TALENTS.KILL_COMMAND_SURVIVAL_TALENT} />
                {t({
                  id: 'hunter.survival.takedown.tipWasteTooltip.p3',
                  message: ' unless spawning a Beast or out of tip stacks/focus.',
                })}
              </>
            }
          >
            (?)
          </TooltipElement>
        </>
      ),
      result: <PerformanceMark perf={tipWastePerf} />,
      details:
        cast.wastedTipStacks > 0 ? (
          <TooltipElement
            content={t({
              id: 'hunter.survival.takedown.wastedStacksDetail',
              message: '{stacks} stack{suffix} wasted',
              values: { stacks: cast.wastedTipStacks, suffix: cast.wastedTipStacks !== 1 ? 's' : '' },
            })}
          >
            (?)
          </TooltipElement>
        ) : null,
    });

    return { checklist: items, perf: overallPerf };
  }
}
